<!-- SPDX-FileCopyrightText: 2026 Carlos Lozano Ruiz -->
<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->

<script>
  // What the app is, what it is built on, and where its source and licence
  // live. A plain panel with no container of its own, so the caller decides
  // whether it appears in a dialog or a routed view.
  //
  // THREE TABS, because the three answer different people. The first is for
  // anyone; the second exists so a bug report carries the versions; the third
  // is the attribution the libraries we ship are owed. A farmer never has to
  // scroll past "WebKitGTK 2.52.3" to reach any of it, which is what the old
  // collapsed <details> was for — a tab says the same thing and says it
  // before the click rather than after.
  //
  // The database path and schema version live HERE now (2026-09-06), for both
  // databases. They were a strip on the Status view; a working screen is not
  // where three constants belong, and this tab was already the place a reader
  // is sent to read facts off.
  import {
    formatDate,
    formatMode,
    formatNumber,
    formatTag,
    languageTag,
    locale,
    nativeName,
    t,
    tCode,
  } from "../i18n.js";
  import { invoke } from "./backend.js";
  import { formatSize } from "./byteSize.js";
  import { run } from "./notifications.svelte.js";
  import TzTabs from "./TzTabs.svelte";
  import Skeleton from "./Skeleton.svelte";
  import { licenceLinkId } from "./thirdParty.js";

  let info = $state(null);

  // get_about_info rather than get_status, and the difference is Android:
  // tauri::webview_version() blocks there until an activity exists, so it must
  // never sit on the startup path. Calling it from a panel the user opened by
  // tapping a button inside the webview means the webview is provably already
  // up (see the command's own doc comment).
  run(async () => {
    info = await invoke("get_about_info");
  });

  // The engine version and the user agent are DIFFERENT facts, so both are
  // shown. WebKitGTK's UA reports a frozen Safari-compatibility version
  // (AppleWebKit/605.1.15 … Version/60.5) that tracks nothing — measured
  // 2026-08-26 against a real engine reporting 2.52.3, and the two even
  // disagree about the distribution. On Android the UA is the one that carries
  // the real Chrome WebView version.
  const userAgent = navigator.userAgent;

  // Ids from the Rust allowlist (src-tauri/src/external_links.rs); labels are
  // `about.link_<id>` in every dictionary.
  // "homepage" is not here: it sits beside the title, labelled with the address
  // itself rather than with a name for it.
  //
  // THE ORDER IS THE LAYOUT. The list is a two-column grid at dialog width and
  // fills row by row, so this array decides the pairs: the licence and the
  // privacy note make the first row — what the app promises the reader — and
  // the two developer-facing links the second. Re-sorting it alphabetically or
  // by "importance" would silently split a pair across rows.
  const LINKS = ["licence", "privacy", "source", "issues"];

  let tab = $state("app");
  const TABS = ["app", "technical", "libraries"];
  const tabItems = $derived(TABS.map((id) => ({ value: id, label: t(`about.tab_${id}`) })));

  function open(id) {
    run(() => invoke("open_external_link", { target: id }));
  }

  // The licence texts, ~90 KB of them, loaded only when the tab is opened —
  // most readers never open it, and none of it belongs in the chunk that has
  // to paint the first screen. Generated by `npm run gen:licences`; JSON
  // rather than a module so the generator never has to escape a legal text.
  let licences = $state(null);

  $effect(() => {
    if (tab !== "libraries" || licences) return;
    import("./thirdPartyLicences.json")
      .then((module) => (licences = module.default))
      // A failed chunk load is the panel's own problem and not a command
      // failure, so it stays out of the bell: the tab keeps its skeleton.
      .catch((err) => console.error(err));
  });

  // How fast the app is actually PAINTED, measured — the one figure on this
  // tab nothing will simply tell us. No browser API exposes a rate, and
  // Tauri's `Monitor` carries name, size, position, work area and scale factor
  // and no rate either, so Rust cannot answer.
  //
  // IT IS FRAMES PER SECOND AND NOT THE PANEL'S Hz, and the difference is
  // measured rather than cautious (2026-09-06, WebKitGTK 2.52.6 on a 60.00 Hz
  // panel per xrandr): the webview paints ~62 fps there, because its rAF is
  // driven by a timer rather than locked to vsync. Printing that as "62 Hz"
  // beside the panel's own resolution would state a hardware fact the hardware
  // contradicts. As fps it is the useful half anyway — the honest answer to
  // "why does this feel slow", where the panel's spec never moves.
  //
  // THE WINDOW MEAN, NOT THE MEDIAN OF THE GAPS, and that is the same
  // measurement's other lesson. WebKitGTK quantises the rAF timestamp to whole
  // milliseconds, so a true 16.67 ms frame arrives as a run of 16s with an
  // occasional 17 — and the median of that is exactly 16 ms, i.e. 62.5 fps, no
  // matter how long you sample. Dividing the elapsed WINDOW by the frames in it
  // leaves a total rounding error of one millisecond spread over all of them.
  let frameRate = $state(null);

  async function measureFrameRate(frames = 48) {
    const stamps = [];
    await new Promise((resolve) => {
      const tick = (at) => {
        stamps.push(at);
        if (stamps.length > frames) resolve();
        else requestAnimationFrame(tick);
      };
      requestAnimationFrame(tick);
    });
    const elapsed = stamps[stamps.length - 1] - stamps[0];
    return elapsed > 0 ? Math.round(((stamps.length - 1) * 1000) / elapsed) : null;
  }

  // Measured when the tab is opened and then kept: it costs about a second of
  // frames, and re-measuring on every visit would make the row flicker by one
  // for no gain. A failure leaves it null, which drops the figure from the row.
  $effect(() => {
    if (tab !== "technical" || frameRate !== null) return;
    measureFrameRate()
      .then((rate) => (frameRate = rate))
      .catch((err) => console.error(err));
  });

  // "3840×2160 at (0, 0) · scale 2 · ~62 fps". One row because it is one
  // question — which screen is this, and how much of it does the app get out
  // of it. The first three come from the platform and the last is measured,
  // which is why it wears a "~" and the unit fps.
  // Every part is a number, so every part goes through formatNumber: a scale
  // factor is 1,5 in Castilian and 1.5 in English.
  const displayText = $derived.by(() => {
    if (!info?.display) return null;
    const { width, height, x, y, scale } = info.display;
    const size = `${formatNumber(width, 0)}×${formatNumber(height, 0)}`;
    const at = t("about.display_at", { x: formatNumber(x, 0), y: formatNumber(y, 0) });
    const parts = [`${size} ${at}`, t("about.display_scale", { scale: formatNumber(scale) })];
    if (frameRate) parts.push(t("about.display_rate", { fps: formatNumber(frameRate, 0) }));
    return parts.join(" · ");
  });

  // The core count is worth having even where the model name is not reported,
  // which is most ARM Linux and Android devices — and every part of this row is
  // independently absent, so each drops on its own rather than taking the row
  // with it. A count that is missing is missing: it is never printed as zero,
  // which is what a phone showed while `threads` could not be null (2026-09-09).
  //
  // Cores ride along with threads or not at all. No platform reports the
  // physical count while failing to report the logical one, so that half has no
  // string of its own to be rendered with.
  const cpuText = $derived.by(() => {
    if (!info) return null;
    const { model, cores, threads } = info.cpu;
    let counts = null;
    if (threads !== null) {
      counts =
        cores !== null
          ? t("about.cpu_cores_threads", {
              cores: formatNumber(cores, 0),
              threads: formatNumber(threads, 0),
            })
          : t("about.cpu_threads", { threads: formatNumber(threads, 0) });
    }
    const parts = [model, counts].filter((part) => part !== null);
    return parts.length > 0 ? parts.join(" · ") : null;
  });

  // Free of the total, because neither figure means much alone: 2 GB free is
  // comfortable on an 8 GB phone and alarming on a 64 GB desktop.
  const memoryText = $derived.by(() =>
    info
      ? t("about.memory_available", {
          available: formatSize(info.memory.available_bytes),
          total: formatSize(info.memory.total_bytes),
        })
      : "…",
  );

  // What this process holds now, and the most it has ever held. The peak is
  // Linux and Android only; where it is missing the row still answers the
  // first half rather than disappearing.
  const processMemoryText = $derived.by(() => {
    if (!info) return "…";
    const { process_bytes: now, process_peak_bytes: peak } = info.memory;
    if (now === null && peak === null) return null;
    const parts = [];
    if (now !== null) parts.push(t("about.memory_now", { size: formatSize(now) }));
    if (peak !== null) parts.push(t("about.memory_peak", { size: formatSize(peak) }));
    return parts.join(" · ");
  });

  // "esquema 12 · 4 MB" under the path. Split from the path rather than joined
  // to it because a path is long and these two are short: on a phone the row
  // would otherwise wrap the size onto a line of its own anyway, unlabelled.
  function databaseNote(database) {
    const parts = [];
    if (database.schema_version !== null) {
      parts.push(t("about.schema", { version: formatNumber(database.schema_version, 0) }));
    }
    if (database.bytes !== null) parts.push(formatSize(database.bytes));
    return parts.join(" · ");
  }

  // What the app is READING the machine as, what language it is showing, and
  // what conventions it is printing figures in — three separate questions the
  // locale work of 2026-08-28 made separate settings, so a report that says
  // "the dates are wrong" needs all three to be answerable.
  //
  // navigator.language is the machine's, resolved by the webview; formatTag()
  // is what Intl is actually formatting with, which is the same thing only
  // while the format mode is "system".
  const systemLocale = navigator.language || "—";

  // A sample of each, because a tag names a convention and does not show it.
  // The date is deliberately the 8th of March: 08/03 and 03/08 are different
  // sentences, which is the whole point.
  const formatSample = $derived(
    `${formatTag()} · ${formatNumber(1234.5)} · ${formatDate("2026-03-08")}`,
  );
</script>

<div class="about">
  <TzTabs items={tabItems} bind:value={tab}>
    {#snippet panel(item)}
      {#if item.value === "app"}
        <!-- A proper noun, so a literal — exactly as App.svelte's brand renders it. -->
        <p class="about-name">
          Terrazgo
          {#if info}
            <!-- Beside the name, and labelled with the address rather than
                 with "Project page": on an About panel the URL is the useful
                 thing to read and to copy. The string comes from the same Rust
                 allowlist the click resolves against, so what is shown and what
                 is opened cannot drift. -->
            <button type="button" class="link-button about-home" onclick={() => open("homepage")}>
              {info.homepage_url}
            </button>
          {/if}
        </p>
        <p class="about-version">{t("about.version", { version: info?.app_version ?? "…" })}</p>

        <p class="about-blurb">{t("about.blurb")}</p>

        <!-- The notice AGPL-3.0 itself asks an application to carry ("How to
             Apply These Terms to Your New Programs"), not a one-line summary of
             it: the copyright line, the grant, the warranty disclaimer, and
             where to find the licence. The licence NAME stays untranslated —
             it is the name of a document, and the only authoritative text is
             the English one the last link points at. -->
        <p class="about-copyright">{t("about.copyright", { year: "2026" })}</p>
        <p class="about-notice">{t("about.notice_grant")}</p>
        <p class="about-notice">{t("about.notice_warranty")}</p>
        <p class="about-notice">{t("about.notice_copy")}</p>

        <!-- Simple links, not framed rows: these are destinations inside a
             sentence-shaped list, and the app already has one way to draw a
             thing that reads as a link (`.link-button`). They stay <button>s —
             an external href would navigate the app window away from itself,
             and Rust holds the URL either way (RegistryHint.svelte). -->
        <ul class="about-links">
          {#each LINKS as id (id)}
            <li>
              <button type="button" class="link-button" onclick={() => open(id)}>
                {t(`about.link_${id}`)}
              </button>
            </li>
          {/each}
        </ul>
      {:else if item.value === "technical"}
        <!-- FOUR GROUPS, because the tab answers four different questions and
             sixteen unbroken rows are a wall: which build is this, what machine
             is it on, where is its data, and what conventions is it printing
             in. The headings reuse the libraries tab's own group styling —
             there is already one way to label a block in this panel.

             The groups are separate <dl>s (a heading is not valid inside one)
             sharing an explicit label column, so the value edges line up across
             all four. -->
        <h4 class="about-group">{t("about.group_build")}</h4>
        <dl class="about-tech">
          <!-- Terrazgo, Tauri and SQLite are proper nouns: literals, not
               dictionary entries. The app's own version leads, because a bug
               report starts with which build it is about — and the row needs no
               label of its own, the column already being "component → version".
               It is also on the first tab; the duplication is deliberate, since
               this is the block that gets copied into a report.

               The build stamp rides in the same row as the version, and that
               is the point of it: through a pre-release the version does not
               move, so "0.1.7" alone does not identify a build while
               "0.1.7 · 2026-09-06T14:22Z" does. It stays in the ISO form Rust
               stamped rather than going through formatDate — this is a build's
               identity, the same kind of string as "2.11.5" beside it, and the
               row's whole job is to be read out or pasted verbatim. -->
          <div>
            <dt>Terrazgo</dt>
            <dd>{info ? `${info.app_version} · ${info.build_time}` : "…"}</dd>
          </div>
          <!-- The identifier is what names the data directory, and the
               packaging is what decides where that directory IS — an AppImage,
               a Flatpak and a .deb put the same id in three different places.
               Together they answer "where did my farms go after the update",
               which is why they share a row. -->
          <div>
            <dt>{t("about.identifier")}</dt>
            <dd>
              {info ? `${info.identifier} · ${tCode("about.packaging", info.packaging)}` : "…"}
            </dd>
          </div>
          <div>
            <dt>Tauri</dt>
            <dd>{info?.tauri_version ?? "…"}</dd>
          </div>
          <div>
            <dt>{t("about.webview")}</dt>
            <dd>{info ? `${info.webview_engine} ${info.webview_version ?? "—"}` : "…"}</dd>
          </div>
          <div>
            <dt>SQLite</dt>
            <dd>{info?.sqlite_version ?? "…"}</dd>
          </div>
        </dl>

        <h4 class="about-group">{t("about.group_machine")}</h4>
        <dl class="about-tech">
          <div>
            <dt>{t("about.system")}</dt>
            <dd>{info?.os ?? "…"}</dd>
          </div>
          <div>
            <dt>{t("about.arch")}</dt>
            <dd>{info?.arch ?? "…"}</dd>
          </div>
          <div>
            <dt>{t("about.cpu")}</dt>
            <dd>{info ? (cpuText ?? "—") : "…"}</dd>
          </div>
          <div>
            <dt>{t("about.memory")}</dt>
            <dd>{memoryText}</dd>
          </div>
          {#if processMemoryText}
            <div>
              <dt>{t("about.process_memory")}</dt>
              <dd>{processMemoryText}</dd>
            </div>
          {/if}
          <div>
            <dt>{t("about.display")}</dt>
            <dd>{info ? (displayText ?? "—") : "…"}</dd>
          </div>
        </dl>

        <h4 class="about-group">{t("about.group_data")}</h4>
        <dl class="about-tech">
          <!-- Both databases, described the same way and side by side, so the
               512 MB one and the irreplaceable one can be told apart before
               anyone deletes the wrong file. -->
          <div>
            <dt>{t("about.database")}</dt>
            <dd>
              {#if info}
                <span class="tech-path">{info.database.path}</span>
                <span class="tech-note">{databaseNote(info.database)}</span>
              {:else}
                …
              {/if}
            </dd>
          </div>
          <div>
            <dt>{t("about.geo_cache")}</dt>
            <dd>
              {#if info}
                <span class="tech-path">{info.geo_cache.path}</span>
                <span class="tech-note">{databaseNote(info.geo_cache)}</span>
              {:else}
                …
              {/if}
            </dd>
          </div>
        </dl>

        <h4 class="about-group">{t("about.group_regional")}</h4>
        <dl class="about-tech">
          <div>
            <dt>{t("about.system_locale")}</dt>
            <dd>{systemLocale}</dd>
          </div>
          <div>
            <dt>{t("about.language")}</dt>
            <dd>{`${nativeName(locale())} · ${languageTag()}`}</dd>
          </div>
          <div>
            <dt>{t("about.formats")}</dt>
            <dd>{`${t(`about.formats_${formatMode()}`)} · ${formatSample}`}</dd>
          </div>
        </dl>

        <p class="about-ua-label">{t("about.user_agent")}</p>
        <p class="about-ua">{userAgent}</p>
      {:else}
        <p class="about-hint">{t("about.libraries_hint")}</p>
        {#if licences}
          {#each licences.licences as licence (licence.spdx)}
            <h4 class="about-group">
              {licence.spdx}
              <button
                type="button"
                class="link-button"
                onclick={() => open(licenceLinkId(licence.spdx))}
              >
                {t("about.licence_canonical")}
              </button>
            </h4>
            <!-- Native <details>: no JS, no library, and it survives the
                 production CSP because it needs neither. Collapsed, because a
                 licence text is a thing to consult and not a thing to read
                 past on the way somewhere else. -->
            {#each licence.texts as entry (entry.packages.join())}
              <details class="lic-box">
                <summary>{entry.projects.join(", ")}</summary>
                <pre class="lic-text">{entry.text}</pre>
              </details>
            {/each}
          {/each}
        {:else}
          <Skeleton />
        {/if}
      {/if}
    {/snippet}
  </TzTabs>
</div>

<style>
  /* The strip stays put while the panel scrolls under it.
     Sticky inside a PADDED scrollport needs all three of these, and the offset
     is the one that is not obvious: `top: 0` resolves against the scrollport's
     CONTENT box, not its padding box, so the strip parked 16px low and a
     licence box's summary was painted in the band above it (measured
     2026-09-04 — `elementFromPoint` in that band answered SUMMARY). Pulling
     `top` up by the body's own inset sticks it flush to the top instead.
     The negative margin then keeps its resting position where it sticks, so
     there is no jump on the first scroll, and its own padding gives back the
     gap. The horizontal pair makes the background reach both edges.

     All three track `--dialog-inset-*` rather than naming a space step,
     because they only work while they equal the scrollport's own padding —
     tuning that padding without these is how the bug comes back. */
  .about :global(.tabrow) {
    position: sticky;
    top: calc(-1 * var(--dialog-inset-y));
    z-index: 1;
    margin: calc(-1 * var(--dialog-inset-y)) calc(-1 * var(--dialog-inset-x)) 0;
    padding: var(--dialog-inset-y) var(--dialog-inset-x) 0;
    background: var(--surface);
  }

  /* The name and the project address on one line, the address riding at the
     name's baseline rather than at its size. */
  .about-name {
    display: flex;
    flex-wrap: wrap;
    gap: var(--space-3);
    align-items: baseline;
    margin: 0;
    font-size: 1.35rem;
    font-weight: 600;
  }

  .about-version {
    margin: var(--space-1) 0 0;
    font-size: 0.875rem;
    color: var(--muted);
  }

  .about-blurb {
    margin: var(--space-3) 0 0;
    font-size: 0.875rem;
  }

  .about-copyright {
    margin: var(--space-3) 0 0;
    font-size: 0.875rem;
  }

  /* The licence notice reads as the small print it is: present, legible, and
     not competing with what the panel is actually for. */
  .about-notice {
    margin: var(--space-1) 0 0;
    font-size: 0.8125rem;
    color: var(--muted);
  }

  .about-home {
    font-size: 0.875rem;
    font-weight: 400;
  }

  /* Two columns where there is room for two: four short destinations in one
     tall column left the panel mostly empty. `auto-fit` rather than a fixed
     two, so the track count follows the width — and the track is 12rem, not 9:
     at 9 the dialog fitted THREE, which is not what a four-item list wants. */
  .about-links {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr));
    gap: var(--space-1) var(--space-4);
    margin: var(--space-3) 0 0;
    padding: 0;
    list-style: none;
    font-size: 0.875rem;
  }

  /* The phone keeps the two columns rather than folding to one. `auto-fit`
     alone gives it one — 12rem is most of a 360px sheet — but these are four
     two-word labels, and stacking them made a menu out of a footnote and put
     the last of them below the fold. Stated as a fixed pair, because at this
     width there is exactly one right answer and no room for a third track.

     700px is the same breakpoint the dialog itself switches on (styles.css →
     the owned modal); below it the panel is a full-screen sheet. */
  @media (max-width: 700px) {
    .about-links {
      grid-template-columns: 1fr 1fr;
    }
  }

  /* Enough to keep the two rows apart and to give the pointer something to
     land on; the old 1.75rem spaced four short links like a menu. */
  .about-links li {
    display: flex;
    min-height: 1.5rem;
    align-items: center;
  }

  /* Versions for a bug report. The one part of the dialog worth copying, so it
     opts out of the app-wide `user-select: none` — the same exception
     `.notif-panel li span` takes, and for the same reason: this text exists to
     be pasted into a bug report. The rest of the dialog, the title included,
     stays unselectable (TzDialog turns bits-ui's text-selection layer off so
     the app rule reaches it). */
  .about-tech,
  .about-ua-label,
  .about-ua {
    font-size: 0.875rem;
    -webkit-user-select: text;
    user-select: text;
  }

  /* The label column is STATED rather than sized to its content (`auto`), and
     that is what lets the four groups be four separate lists: each `auto`
     column would size to its own longest label, and the value edges would step
     in and out down the tab. 8.5rem fits the longest label in all three
     languages ("Identificador", "Memòria del procés") at this size; a longer
     one wraps rather than pushing the values across. */
  .about-tech {
    display: grid;
    grid-template-columns: minmax(0, 8.5rem) 1fr;
    gap: var(--space-1) var(--space-4);
    margin: 0 0 var(--space-3);
  }

  /* Each row is a <div> wrapping its dt/dd so the pairs stay together; display
     them as contents so the grid columns line up across rows. */
  .about-tech div {
    display: contents;
  }

  .about-tech dt {
    color: var(--muted);
  }

  .about-tech dd {
    margin: 0;
  }

  /* A database path is one long unbroken token, like the user agent below, and
     breaks anywhere rather than pushing the dialog into a sideways scroll. */
  .tech-path {
    display: block;
    overflow-wrap: anywhere;
  }

  /* The schema version and the size, under the path they belong to: short
     facts about a long one, and muted so the path stays the row's subject. */
  .tech-note {
    display: block;
    font-size: 0.8125rem;
    color: var(--muted);
  }

  .about-ua-label {
    margin: 0 0 var(--space-1);
    color: var(--muted);
  }

  /* The user agent is one long unbroken token; let it wrap anywhere rather than
     push the dialog into a sideways scroll. */
  .about-ua {
    margin: 0;
    font-family: ui-monospace, monospace;
    font-size: 0.8125rem;
    overflow-wrap: anywhere;
  }

  /* A licence text: consulted, not read past, so it opens on demand and gets a
     scroller of its own rather than pushing 11 KB of Apache-2.0 through the
     dialog's. */
  .lic-box {
    border-bottom: 1px solid var(--border);
  }

  .lic-box summary {
    padding: 0.35rem 0;
    font-size: 0.875rem;
    cursor: pointer;
  }

  .lic-text {
    max-height: 16rem;
    margin: 0 0 var(--space-3);
    /* Vertical only: pre-wrap with `overflow-wrap: anywhere` never overflows
       sideways, so there is no horizontal scroll to opt out of. */
    overflow-y: auto;
    overscroll-behavior-y: none;
    font-family: ui-monospace, monospace;
    font-size: 0.75rem;
    line-height: 1.45;
    white-space: pre-wrap;
    overflow-wrap: anywhere;
    color: var(--muted);
    /* The one thing here anyone would ever want to copy. */
    -webkit-user-select: text;
    user-select: text;
  }

  .about-hint {
    margin: 0 0 var(--space-3);
    font-size: 0.875rem;
    color: var(--muted);
  }

  .about-group {
    display: flex;
    gap: var(--space-3);
    align-items: baseline;
    justify-content: space-between;
    margin: var(--space-4) 0 var(--space-2);
    font-size: 0.75rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--muted);
  }

  .about-group:first-of-type {
    margin-top: 0;
  }
</style>
