<!-- SPDX-FileCopyrightText: 2026 Carlos Lozano Ruiz -->
<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->

<script>
  // What the app is, what it is built on, and where its source and licence
  // live. A plain panel with no container of its own, so the caller decides
  // whether it appears in a dialog or a routed view.
  //
  // THREE TABS, because the three answer different people. The first is for
  // anyone; the second exists so a bug report carries the versions; the third
  // is the attribution the libraries we ship are owed. A farmer never has to
  // scroll past "WebKitGTK 2.52.3" to reach any of it, which is what the old
  // collapsed <details> was for — a tab says the same thing and says it
  // before the click rather than after.
  //
  // Deliberately NOT repeated here: the database path and schema version.
  // Those are the Status view's, and a second copy would be a second thing to
  // keep true.
  import { t } from "../i18n.js";
  import { invoke } from "./backend.js";
  import { run } from "./notifications.svelte.js";
  import TzTabs from "./TzTabs.svelte";
  import Skeleton from "./Skeleton.svelte";
  import { licenceLinkId } from "./thirdParty.js";

  let info = $state(null);

  // get_about_info rather than get_status, and the difference is Android:
  // tauri::webview_version() blocks there until an activity exists, so it must
  // never sit on the startup path. Calling it from a panel the user opened by
  // tapping a button inside the webview means the webview is provably already
  // up (see the command's own doc comment).
  run(async () => {
    info = await invoke("get_about_info");
  });

  // The engine version and the user agent are DIFFERENT facts, so both are
  // shown. WebKitGTK's UA reports a frozen Safari-compatibility version
  // (AppleWebKit/605.1.15 … Version/60.5) that tracks nothing — measured
  // 2026-08-26 against a real engine reporting 2.52.3, and the two even
  // disagree about the distribution. On Android the UA is the one that carries
  // the real Chrome WebView version.
  const userAgent = navigator.userAgent;

  // Ids from the Rust allowlist (src-tauri/src/external_links.rs); labels are
  // `about.link_<id>` in every dictionary.
  // "homepage" is not here: it sits beside the title, labelled with the address
  // itself rather than with a name for it.
  //
  // THE ORDER IS THE LAYOUT. The list is a two-column grid at dialog width and
  // fills row by row, so this array decides the pairs: the licence and the
  // privacy note make the first row — what the app promises the reader — and
  // the two developer-facing links the second. Re-sorting it alphabetically or
  // by "importance" would silently split a pair across rows.
  const LINKS = ["licence", "privacy", "source", "issues"];

  let tab = $state("app");
  const TABS = ["app", "technical", "libraries"];
  const tabItems = $derived(TABS.map((id) => ({ value: id, label: t(`about.tab_${id}`) })));

  function open(id) {
    run(() => invoke("open_external_link", { target: id }));
  }

  // The licence texts, ~88 KB of them, loaded only when the tab is opened —
  // most readers never open it, and none of it belongs in the chunk that has
  // to paint the first screen. Generated by `npm run gen:licences`; JSON
  // rather than a module so the generator never has to escape a legal text.
  let licences = $state(null);

  $effect(() => {
    if (tab !== "libraries" || licences) return;
    import("./thirdPartyLicences.json")
      .then((module) => (licences = module.default))
      // A failed chunk load is the panel's own problem and not a command
      // failure, so it stays out of the bell: the tab keeps its skeleton.
      .catch((err) => console.error(err));
  });
</script>

<div class="about">
  <TzTabs items={tabItems} bind:value={tab}>
    {#snippet panel(item)}
      {#if item.value === "app"}
        <!-- A proper noun, so a literal — exactly as App.svelte's brand renders it. -->
        <p class="about-name">
          Terrazgo
          {#if info}
            <!-- Beside the name, and labelled with the address rather than
                 with "Project page": on an About panel the URL is the useful
                 thing to read and to copy. The string comes from the same Rust
                 allowlist the click resolves against, so what is shown and what
                 is opened cannot drift. -->
            <button type="button" class="link-button about-home" onclick={() => open("homepage")}>
              {info.homepage_url}
            </button>
          {/if}
        </p>
        <p class="about-version">{t("about.version", { version: info?.app_version ?? "…" })}</p>

        <p class="about-blurb">{t("about.blurb")}</p>

        <!-- The notice AGPL-3.0 itself asks an application to carry ("How to
             Apply These Terms to Your New Programs"), not a one-line summary of
             it: the copyright line, the grant, the warranty disclaimer, and
             where to find the licence. The licence NAME stays untranslated —
             it is the name of a document, and the only authoritative text is
             the English one the last link points at. -->
        <p class="about-copyright">{t("about.copyright", { year: "2026" })}</p>
        <p class="about-notice">{t("about.notice_grant")}</p>
        <p class="about-notice">{t("about.notice_warranty")}</p>
        <p class="about-notice">{t("about.notice_copy")}</p>

        <!-- Simple links, not framed rows: these are destinations inside a
             sentence-shaped list, and the app already has one way to draw a
             thing that reads as a link (`.link-button`). They stay <button>s —
             an external href would navigate the app window away from itself,
             and Rust holds the URL either way (RegistryHint.svelte). -->
        <ul class="about-links">
          {#each LINKS as id (id)}
            <li>
              <button type="button" class="link-button" onclick={() => open(id)}>
                {t(`about.link_${id}`)}
              </button>
            </li>
          {/each}
        </ul>
      {:else if item.value === "technical"}
        <dl class="about-tech">
          <!-- Terrazgo, Tauri and SQLite are proper nouns: literals, not
               dictionary entries. The app's own version leads, because a bug
               report starts with which build it is about — and the row needs no
               label of its own, the column already being "component → version".
               It is also on the first tab; the duplication is deliberate, since
               this is the block that gets copied into a report. -->
          <div>
            <dt>Terrazgo</dt>
            <dd>{info?.app_version ?? "…"}</dd>
          </div>
          <div>
            <dt>Tauri</dt>
            <dd>{info?.tauri_version ?? "…"}</dd>
          </div>
          <div>
            <dt>{t("about.webview")}</dt>
            <dd>{info ? `${info.webview_engine} ${info.webview_version ?? "—"}` : "…"}</dd>
          </div>
          <div>
            <dt>SQLite</dt>
            <dd>{info?.sqlite_version ?? "…"}</dd>
          </div>
          <div>
            <dt>{t("about.system")}</dt>
            <dd>{info?.os ?? "…"}</dd>
          </div>
          <div>
            <dt>{t("about.arch")}</dt>
            <dd>{info?.arch ?? "…"}</dd>
          </div>
        </dl>
        <p class="about-ua-label">{t("about.user_agent")}</p>
        <p class="about-ua">{userAgent}</p>
      {:else}
        <p class="about-hint">{t("about.libraries_hint")}</p>
        {#if licences}
          {#each licences.licences as licence (licence.spdx)}
            <h4 class="about-group">
              {licence.spdx}
              <button
                type="button"
                class="link-button"
                onclick={() => open(licenceLinkId(licence.spdx))}
              >
                {t("about.licence_canonical")}
              </button>
            </h4>
            <!-- Native <details>: no JS, no library, and it survives the
                 production CSP because it needs neither. Collapsed, because a
                 licence text is a thing to consult and not a thing to read
                 past on the way somewhere else. -->
            {#each licence.texts as entry (entry.packages.join())}
              <details class="lic-box">
                <summary>{entry.projects.join(", ")}</summary>
                <pre class="lic-text">{entry.text}</pre>
              </details>
            {/each}
          {/each}
        {:else}
          <Skeleton />
        {/if}
      {/if}
    {/snippet}
  </TzTabs>
</div>

<style>
  /* The strip stays put while the panel scrolls under it.
     Sticky inside a PADDED scrollport needs all three of these, and the offset
     is the one that is not obvious: `top: 0` resolves against the scrollport's
     CONTENT box, not its padding box, so the strip parked 16px low and a
     licence box's summary was painted in the band above it (measured
     2026-09-04 — `elementFromPoint` in that band answered SUMMARY). Pulling
     `top` up by the body's own inset sticks it flush to the top instead.
     The negative margin then keeps its resting position where it sticks, so
     there is no jump on the first scroll, and its own padding gives back the
     gap. The horizontal pair makes the background reach both edges.

     All three track `--dialog-inset-*` rather than naming a space step,
     because they only work while they equal the scrollport's own padding —
     tuning that padding without these is how the bug comes back. */
  .about :global(.tabrow) {
    position: sticky;
    top: calc(-1 * var(--dialog-inset-y));
    z-index: 1;
    margin: calc(-1 * var(--dialog-inset-y)) calc(-1 * var(--dialog-inset-x)) 0;
    padding: var(--dialog-inset-y) var(--dialog-inset-x) 0;
    background: var(--surface);
  }

  /* The name and the project address on one line, the address riding at the
     name's baseline rather than at its size. */
  .about-name {
    display: flex;
    flex-wrap: wrap;
    gap: var(--space-3);
    align-items: baseline;
    margin: 0;
    font-size: 1.35rem;
    font-weight: 600;
  }

  .about-version {
    margin: var(--space-1) 0 0;
    font-size: 0.875rem;
    color: var(--muted);
  }

  .about-blurb {
    margin: var(--space-3) 0 0;
    font-size: 0.875rem;
  }

  .about-copyright {
    margin: var(--space-3) 0 0;
    font-size: 0.875rem;
  }

  /* The licence notice reads as the small print it is: present, legible, and
     not competing with what the panel is actually for. */
  .about-notice {
    margin: var(--space-1) 0 0;
    font-size: 0.8125rem;
    color: var(--muted);
  }

  .about-home {
    font-size: 0.875rem;
    font-weight: 400;
  }

  /* Two columns where there is room for two: four short destinations in one
     tall column left the panel mostly empty. `auto-fit` rather than a fixed
     two, so the phone sheet folds back to one instead of hyphenating — and the
     track is 12rem, not 9: at 9 the dialog fitted THREE, which is not what a
     four-item list wants. */
  .about-links {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(12rem, 1fr));
    gap: var(--space-1) var(--space-4);
    margin: var(--space-3) 0 0;
    padding: 0;
    list-style: none;
    font-size: 0.875rem;
  }

  /* Enough to keep the two rows apart and to give the pointer something to
     land on; the old 1.75rem spaced four short links like a menu. */
  .about-links li {
    display: flex;
    min-height: 1.5rem;
    align-items: center;
  }

  /* Versions for a bug report. The one part of the dialog worth copying, so it
     opts out of the app-wide `user-select: none` — the same exception
     `.notif-panel li span` takes, and for the same reason: this text exists to
     be pasted into a bug report. The rest of the dialog, the title included,
     stays unselectable (TzDialog turns bits-ui's text-selection layer off so
     the app rule reaches it). */
  .about-tech,
  .about-ua-label,
  .about-ua {
    font-size: 0.875rem;
    -webkit-user-select: text;
    user-select: text;
  }

  .about-tech {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: var(--space-1) var(--space-4);
    margin: 0 0 var(--space-3);
  }

  /* Each row is a <div> wrapping its dt/dd so the pairs stay together; display
     them as contents so the grid columns line up across rows. */
  .about-tech div {
    display: contents;
  }

  .about-tech dt {
    color: var(--muted);
  }

  .about-tech dd {
    margin: 0;
  }

  .about-ua-label {
    margin: 0 0 var(--space-1);
    color: var(--muted);
  }

  /* The user agent is one long unbroken token; let it wrap anywhere rather than
     push the dialog into a sideways scroll. */
  .about-ua {
    margin: 0;
    font-family: ui-monospace, monospace;
    font-size: 0.8125rem;
    overflow-wrap: anywhere;
  }

  /* A licence text: consulted, not read past, so it opens on demand and gets a
     scroller of its own rather than pushing 11 KB of Apache-2.0 through the
     dialog's. */
  .lic-box {
    border-bottom: 1px solid var(--border);
  }

  .lic-box summary {
    padding: 0.35rem 0;
    font-size: 0.875rem;
    cursor: pointer;
  }

  .lic-text {
    max-height: 16rem;
    margin: 0 0 var(--space-3);
    overflow: auto;
    font-family: ui-monospace, monospace;
    font-size: 0.75rem;
    line-height: 1.45;
    white-space: pre-wrap;
    overflow-wrap: anywhere;
    color: var(--muted);
    /* The one thing here anyone would ever want to copy. */
    -webkit-user-select: text;
    user-select: text;
  }

  .about-hint {
    margin: 0 0 var(--space-3);
    font-size: 0.875rem;
    color: var(--muted);
  }

  .about-group {
    display: flex;
    gap: var(--space-3);
    align-items: baseline;
    justify-content: space-between;
    margin: var(--space-4) 0 var(--space-2);
    font-size: 0.75rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    color: var(--muted);
  }

  .about-group:first-of-type {
    margin-top: 0;
  }
</style>
